// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ99p_NcfKp20aGSY0imhu2PnBK8DWhqI',
    appId: '1:655896667420:web:af67264faa09f97e54c6d9',
    messagingSenderId: '655896667420',
    projectId: 'finearts-b3f72',
    authDomain: 'finearts-b3f72.firebaseapp.com',
    databaseURL: 'https://finearts-b3f72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finearts-b3f72.appspot.com',
    measurementId: 'G-DBDBWN4SKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNuSnJw7LGU9g85hXSDHhKzlDeuM0lfHY',
    appId: '1:655896667420:android:c3c52747e0b3e28454c6d9',
    messagingSenderId: '655896667420',
    projectId: 'finearts-b3f72',
    databaseURL: 'https://finearts-b3f72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finearts-b3f72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMOttpyNE71-iOlJWmjwIr8dh7r_colZc',
    appId: '1:655896667420:ios:fadaf99adfdbc38554c6d9',
    messagingSenderId: '655896667420',
    projectId: 'finearts-b3f72',
    databaseURL: 'https://finearts-b3f72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finearts-b3f72.appspot.com',
    iosBundleId: 'com.example.fineArts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMOttpyNE71-iOlJWmjwIr8dh7r_colZc',
    appId: '1:655896667420:ios:43290ee5c266abe254c6d9',
    messagingSenderId: '655896667420',
    projectId: 'finearts-b3f72',
    databaseURL: 'https://finearts-b3f72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'finearts-b3f72.appspot.com',
    iosBundleId: 'com.example.fineArts.RunnerTests',
  );
}
